package surfline

//Query Response struct
//Generated by https://mholt.github.io/json-to-go/
type sourceStruct struct {
	BreadCrumbs []string `json:"breadCrumbs"`
	Name        string   `json:"name"`
	Location    struct {
		Lon float64 `json:"lon"`
		Lat float64 `json:"lat"`
	} `json:"location"`
	Cams []interface{} `json:"cams"`
	Href string        `json:"href"`
}

type queryResp []struct {
	Took     int  `json:"took"`
	TimedOut bool `json:"timed_out"`
	Shards   struct {
		Total      int `json:"total"`
		Successful int `json:"successful"`
		Failed     int `json:"failed"`
	} `json:"_shards"`
	Hits struct {
		Total    int     `json:"total"`
		MaxScore float64 `json:"max_score"`
		Hits     []struct {
			Index  string       `json:"_index"`
			Type   string       `json:"_type"`
			ID     string       `json:"_id"`
			Score  float64      `json:"_score"`
			Source sourceStruct `json:"_source"`
		} `json:"hits"`
	} `json:"hits"`
	Suggest struct {
		SpotSuggest []struct {
			Text    string `json:"text"`
			Offset  int    `json:"offset"`
			Length  int    `json:"length"`
			Options []struct {
				Text     string       `json:"text"`
				Index    string       `json:"_index"`
				Type     string       `json:"_type"`
				ID       string       `json:"_id"`
				Score    int          `json:"_score"`
				Source   sourceStruct `json:"_source"`
				Contexts struct {
					Type     []string `json:"type"`
					Location []string `json:"location"`
				} `json:"contexts"`
			} `json:"options"`
		} `json:"spot-suggest"`
	} `json:"suggest"`
	Status int `json:"status"`
}
